# Generated by Django 5.1.2 on 2024-11-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
