# Generated by Django 5.1.2 on 2024-11-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_name_post_title_remove_post_weight_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
    ]
